theme = "tokyonight"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["file-encoding", "file-type"]
separator = " | "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
