ZSH=$HOME/dotfiles/oh-my-zsh
ZSH_THEME=""
ZSH_CUSTOM=$HOME/dotfiles/zsh/zsh-custom
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_PATTERNS=('rm -rf *' 'fg=white,bold,bg=red')

plugins=(
	zsh-autosuggestions
	zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# AUTO CD
setopt auto_cd

#TYPO CORRECTION
unsetopt correct_all

#SOURCING
for file in $HOME/dotfiles/zsh/sourced/*; do
	source "$file"
done

bindkey -v
bindkey -M viins 'jj' vi-cmd-mode
function zle-line-init zle-keymap-select {
    RPS2=$RPS1
    zle reset-prompt
}
bindkey "^?" backward-delete-char

zle -N zle-line-init
zle -N zle-keymap-select

#HISTORY
HISTFILE=~/.zsh_history
SAVEHIST=1000
setopt inc_append_history
setopt share_history

# if [ -t 0 ] && [[ -z $TMUX ]] && [[ $- = *i* ]]; then exec tmux; fi
#neofetch --ascii ~/.config/neofetch/picture

#PURE THEME
autoload -U promptinit; promptinit
prompt pure
export PATH="/usr/local/opt/libxml2/bin:$PATH"
alias mf-gen="/bin/sh ~/42-utilities/update.sh; python3 ~/42-utilities/mf-gen.py"
alias proto-list="/bin/sh ~/42-utilities/update.sh; sh ~/42-utilities/proto-list.sh"
